live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x15161e"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[cursor]
blink_interval = 750
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "Beam"

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 12.0

[font.normal]
family = "Source Code Pro"

[keyboard]
bindings = [
    { key = "Copy", action = "Copy" },
    { key = "Paste", action = "Paste" },
    { key = "PageUp", mods = "Shift", mode = "~Alt", action = "ScrollPageUp" },
    { key = "PageDown", mods = "Shift", mode = "~Alt", action = "ScrollPageDown" },
    { key = "Home", mods = "Shift", mode = "~Alt", action = "ScrollToTop" },
    { key = "End", mods = "Shift", mode = "~Alt", action = "ScrollToBottom" },
    # Vi Mode
    { key = "Escape", mods = "Alt", mode = "Vi|~Search", action = "ScrollToBottom" },
    { key = "Escape", mods = "Alt", mode = "~Search", action = "ToggleViMode" },
    { key = "Escape", mode = "Vi|~Search", action = "ClearSelection" },
    { key = "I", mode = "Vi|~Search", action = "ScrollToBottom" },
    { key = "I", mode = "Vi|~Search", action = "ToggleViMode" },
    { key = "Y", mods = "Control", mode = "Vi|~Search", action = "ScrollLineUp" },
    { key = "E", mods = "Control", mode = "Vi|~Search", action = "ScrollLineDown" },
    { key = "G", mode = "Vi|~Search", action = "ScrollToTop" },
    { key = "G", mods = "Shift", mode = "Vi|~Search", action = "ScrollToBottom" },
    { key = "B", mods = "Control", mode = "Vi|~Search", action = "ScrollPageUp" },
    { key = "F", mods = "Control", mode = "Vi|~Search", action = "ScrollPageDown" },
    { key = "U", mods = "Control", mode = "Vi|~Search", action = "ScrollHalfPageUp" },
    { key = "D", mods = "Control", mode = "Vi|~Search", action = "ScrollHalfPageDown" },
    { key = "Y", mode = "Vi|~Search", action = "Copy" },
    { key = "Y", mode = "Vi|~Search", action = "ClearSelection" },
    { key = "V", mode = "Vi|~Search", action = "ToggleNormalSelection" },
    { key = "V", mods = "Shift", mode = "Vi|~Search", action = "ToggleLineSelection" },
    { key = "V", mods = "Control", mode = "Vi|~Search", action = "ToggleBlockSelection" },
    { key = "V", mods = "Alt", mode = "Vi|~Search", action = "ToggleSemanticSelection" },
    { key = "Return", mode = "Vi|~Search", action = "Open" },
    { key = "K", mode = "Vi|~Search", action = "Up" },
    { key = "J", mode = "Vi|~Search", action = "Down" },
    { key = "H", mode = "Vi|~Search", action = "Left" },
    { key = "L", mode = "Vi|~Search", action = "Right" },
    { key = "Key0", mode = "Vi|~Search", action = "First" },
    { key = "Key4", mods = "Shift", mode = "Vi|~Search", action = "Last" },
    { key = "Key6", mods = "Shift", mode = "Vi|~Search", action = "FirstOccupied" },
    { key = "H", mods = "Shift", mode = "Vi|~Search", action = "High" },
    { key = "M", mods = "Shift", mode = "Vi|~Search", action = "Middle" },
    { key = "L", mods = "Shift", mode = "Vi|~Search", action = "Low" },
    { key = "B", mode = "Vi|~Search", action = "SemanticLeft" },
    { key = "W", mode = "Vi|~Search", action = "SemanticRight" },
    { key = "E", mode = "Vi|~Search", action = "SemanticRightEnd" },
    { key = "B", mods = "Shift", mode = "Vi|~Search", action = "WordLeft" },
    { key = "W", mods = "Shift", mode = "Vi|~Search", action = "WordRight" },
    { key = "E", mods = "Shift", mode = "Vi|~Search", action = "WordRightEnd" },
    { key = "Key5", mods = "Shift", mode = "Vi|~Search", action = "Bracket" },
    { key = "Slash", mode = "Vi|~Search", action = "SearchForward" },
    { key = "Slash", mods = "Shift", mode = "Vi|~Search", action = "SearchBackward" },
    { key = "N", mode = "Vi|~Search", action = "SearchNext" },
    { key = "N", mods = "Shift", mode = "Vi|~Search", action = "SearchPrevious" },
    # Search Mode
    { key = "Return", mode = "Search|Vi", action = "SearchConfirm" },
    { key = "Escape", mode = "Search", action = "SearchCancel" },
    { key = "C", mods = "Control", mode = "Search", action = "SearchCancel" },
    { key = "U", mods = "Control", mode = "Search", action = "SearchClear" },
    { key = "W", mods = "Control", mode = "Search", action = "SearchDeleteWord" },
    { key = "P", mods = "Control", mode = "Search", action = "SearchHistoryPrevious" },
    { key = "N", mods = "Control", mode = "Search", action = "SearchHistoryNext" },
    { key = "V", mods = "Control|Shift", mode = "~Vi", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "F", mods = "Control|Shift", mode = "~Search", action = "SearchForward" },
    { key = "B", mods = "Control|Shift", mode = "~Search", action = "SearchBackward" },
    { key = "C", mods = "Control|Shift", mode = "Vi|~Search", action = "ClearSelection" },
    { key = "Insert", mods = "Shift", action = "PasteSelection" },
    { key = "Key0", mods = "Control", action = "ResetFontSize" },
    { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
]

[scrolling]
history = 50000
multiplier = 5

[window]
decorations = "none"
opacity = 0.95

[window.dimensions]
columns = 80
lines = 24
