# vim: ft=zsh ts=2 sw=0

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

# Custom path
export PATH="$HOME/bin:$PATH"
export PATH="$PATH:$HOME/.dotnet/tools"

# Firefox
export MOZ_USE_XINPUT2=1

export BROWSER=zen-browser
export EDITOR=nvim

# Man
export MANPAGER="less -R --use-color -Dd+g -Du+r"
export MANROFFOPT="-P -c"

export LESS='-i -n -R -F -X'

export TERMINFO="$XDG_DATA_HOME"/terminfo
export TERMINFO_DIRS="$XDG_DATA_HOME"/terminfo:/usr/share/terminfo

export GOPATH="$XDG_DATA_HOME/go"

export GNUPGHOME="$XDG_DATA_HOME"/gnupg

# Flutter and Android
export PATH="$HOME/flutter/bin:$PATH"
export ANDROID_SDK_ROOT="$HOME/Android"
export ANDROID_HOME="$HOME/Android"

# Rust
export PATH="$HOME/.cargo/bin:$PATH"

# Local
export PATH="$HOME/.local/bin:$PATH"

export WIND=/mnt/c/Users/sero
