#!/bin/bash

LANG=en_DK.UTF-8

start_once(){ pgrep -x "$1" > /dev/null || ("$@" &) }
$HOME/bin/keyboard
killall -q sxhkd; sxhkd -c $HOME/.config/sxhkd/sxhkdrc &

if [ $(hostname) = 'desks' ]; then
    bspc monitor DP-2 -d 1 3 5 7 9
    bspc monitor HDMI-0 -d 2 4 6 8 10

    xwallpaper  --output DP-2 --center $HOME/.local/wallpapers/mountain-1440p.jpg \
        --output HDMI-0 --center $HOME/.local/wallpapers/mountain-1440p.jpg

elif [ $(hostname) = 'bloks' ]; then
    bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
    xwallpaper --output eDP1 --center $HOME/.local/wallpapers/house.jpg
else
    bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
    xwallpaper --output eDP1 --center $HOME/.local/wallpapers/purple.jpg
fi

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config single_monocle       true
# Focus window on hover
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
# bspc config pointer_follows_focus true

bspc config  focused_border_color "#3D84CB"

bspc rule -a Simplenote state=floating
bspc rule -a qBittorrent state=floating
bspc rule -a Sxiv       state=floating
bspc rule -a Nsxiv       state=floating
bspc rule -a Bluetooth state=floating follow=on
bspc rule -a feh state=floating follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a TelegramDesktop state=floating
bspc rule -a *:floating state=floating
bspc rule -a Signal state=floating
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Pavucontrol state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Nm-connection-editor state=floating

bspc rule -a Zathura state=tiled

# Init programs
start_once redshift -l $(<$HOME/.config/redshift/location.txt)
start_once picom
# pgrep telegram || DESKTOP_APP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY=1 telegram-desktop -startintray &

# Polybar and hacks
$HOME/.config/polybar/launch.sh &
start_once xbanish
start_once unclutter
start_once nm-applet
start_once blueman-applet

