#!/bin/bash

start_once(){ pgrep -x "$1" > /dev/null || ("$@" &) }
start_once sxhkd

if [ $(hostname) = 'desks' ]; then
    bspc monitor DP-4 -d 1 3 5 7 9
    bspc monitor DP-2 -d 2 4 6 8 10
    xwallpaper  --output DP-4 --center $HOME/.local/wallpapers/mountain-1440p.jpg \
        --output DP-2 --center $HOME/.local/wallpapers/train.jpg &
elif [ $(hostname) = 'bloks' ]; then
    bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
    xwallpaper --output eDP1 --center $HOME/.local/wallpapers/house.jpg
fi

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config single_monocle       true
# Focus window on hover
bspc config focus_follows_pointer true
# bspc config pointer_follows_focus true

bspc config  focused_border_color "#3D84CB"

bspc rule -a qBittorrent state=floating
bspc rule -a Sxiv       state=floating
bspc rule -a Bluetooth state=floating follow=on
bspc rule -a feh state=floating follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a TelegramDesktop state=floating
bspc rule -a *:floating state=floating
bspc rule -a Signal state=floating
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Pavucontrol state=floating

bspc rule -a Zathura state=tiled

# Init programs
start_once redshift -l $(<$HOME/.config/redshift/location.txt)
start_once picom
pgrep telegram || LOCALE=en_UK.UTF8 \
    DESKTOP_APP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY=1 telegram-desktop -startintray &

# Polybar and hacks
$HOME/.config/polybar/launch.sh
sleep 0.5 && xdo above -t $(xdo id -n root) $(xdo id -n tray) \
    && xdo above -t $(xdo id -n root) $(xdo id -n polybar)

$HOME/bin/keyboard
xbanish &
unclutter &
